# Generated by Django 5.2.8 on 2026-07-26 22:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActuWebApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='titre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug(URL)')),
                ('summary', models.TextField(help_text='Un resume court pour les cartes actualites', max_length=500, verbose_name='Resume')),
                ('content', models.TextField(max_length=100, verbose_name="Contenu de l'article")),
                ('image', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('actualites', 'actualites'), ('sports', 'sports'), ('politiques', 'politiques')], default='actualites', max_length=20, verbose_name='Categories')),
                ('sources', models.CharField(blank=True, help_text='Exemple: lemonde, AFP, Reuters(separes des virgules)', max_length=255, null=True)),
                ('status', models.CharField(choices=[('brouillon', 'brouillon'), ('publie', 'publie')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de creation')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='date de modification')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de publication')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': ['article'],
                'verbose_name_plural': ['articles'],
                'ordering': ['-published_at'],
            },
        ),
    ]
