# Generated by Django 5.2.8 on 2026-08-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActuWebApp', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('artiste', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('kompa', 'Kompa'), ('rap', 'Rap'), ('afrobeat', 'Afrobeat'), ('rnb', 'RNB'), ('gospel', 'Gospel'), ('racine', 'Musique Racine'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('audio_url', models.URLField(help_text='Lien direct vers le fichier', max_length=500)),
                ('image_url', models.URLField(blank=True, help_text='Pochette (Bunny.net ou autre CDN)', max_length=500)),
                ('nb_ecoutes', models.PositiveIntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Musique',
                'verbose_name_plural': 'Musiques',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name="Contenu de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name="Adresse URL de l'image"),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(help_text='Un resume court pour les cartes actualites', max_length=200, verbose_name='Resume'),
        ),
    ]
