# Generated by Django 5.2.8 on 2026-08-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActuWebApp', '0005_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='photo',
            field=models.CharField(blank=True, choices=[('avatar-1', 'avatar-1'), ('avatar-2', 'avatar-2'), ('avatar-3 (Masculin)', 'avatar-3 (Masculin)'), ('avatar-4 (Feminin)', 'avatar-4 (Feminin)'), ('avatar-5', 'avatar-5')], default='https://i.pravatar.cc/150?img=1', max_length=50),
        ),
    ]
