# Generated by Django 5.2.8 on 2026-08-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActuWebApp', '0006_alter_profil_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='datenaissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
