# Generated by Django 5.2.8 on 2026-08-17 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActuWebApp', '0007_alter_profil_datenaissance_alter_profil_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='musique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='ActuWebApp.musiques'),
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, null=True)),
                ('contenu_lrc', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('musique', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='ActuWebApp.musiques')),
            ],
        ),
    ]
