# Generated by Django 5.2.8 on 2026-08-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActuWebApp', '0008_alter_commentaire_musique_lyric'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaineTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.URLField(help_text='Lien vers la chaine..', max_length=300)),
                ('logo', models.URLField(help_text='Logo de la chaine..', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('actualites', 'actualites'), ('sports', 'sports'), ('sante', 'sante'), ('sciences', 'sciences'), ('politiques', 'politiques')], default='actualites', max_length=20, verbose_name='Categories'),
        ),
    ]
