# Generated by Django 5.2.8 on 2026-08-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActuWebApp', '0009_chainetv_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainetv',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
    ]
