# Generated by Django 5.2.8 on 2026-08-25 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActuWebApp', '0010_chainetv_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chainetv',
            options={'verbose_name': 'ChaineTV', 'verbose_name_plural': 'ChainesTV'},
        ),
        migrations.AlterField(
            model_name='chainetv',
            name='nom',
            field=models.CharField(max_length=200, null='True', verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='chainetv',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('morceaux', models.ManyToManyField(blank=True, related_name='playlists', to='ActuWebApp.musiques')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
