# Generated by Django 5.2.8 on 2026-09-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActuWebApp', '0011_alter_chainetv_options_alter_chainetv_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainetv',
            name='categorie',
            field=models.CharField(blank=True, choices=[('info', 'Info'), ('sport', 'Sport'), ('musique', 'Musique'), ('culture', 'Culture'), ('generaliste', 'Generaliste'), ('divertissement', 'Divertissement')], help_text='Categorie', max_length=300, null=True, verbose_name='categorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('actualites', 'actualites'), ('sports', 'sports'), ('sante', 'sante'), ('sciences', 'sciences'), ('politiques', 'politiques'), ('musiques', 'musiques')], default='actualites', max_length=20, verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='chainetv',
            name='nom',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='chainetv',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
    ]
