# Generated by Django 5.2.8 on 2026-09-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActuWebApp', '0012_chainetv_categorie_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainetv',
            name='categorie',
            field=models.CharField(blank=True, choices=[('info', 'Info'), ('sport', 'Sport'), ('musique', 'Musique'), ('culture', 'Culture'), ('generaliste', 'Generaliste'), ('divertissement', 'Divertissement')], default='info', help_text='Categorie', max_length=300, null=True, verbose_name='categorie'),
        ),
    ]
